"""SQLAlchemy Core schema for the warehouse runtime."""

from __future__ import annotations

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Numeric,
    PrimaryKeyConstraint,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)


metadata = MetaData(
    naming_convention={
        "ix": "ix_%(table_name)s_%(column_0_name)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
)

ads_profile = Table(
    "ads_profile",
    metadata,
    Column("profile_id", String(64), primary_key=True),
    Column("region", String(8), nullable=False),
    Column("country_code", String(8), nullable=True),
    Column("account_type", String(64), nullable=True),
    Column("account_name", String(255), nullable=True),
    Column("currency_code", String(16), nullable=True),
    Column("timezone", String(128), nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_refreshed_at", DateTime(timezone=True), nullable=False),
)

portfolio = Table(
    "portfolio",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("portfolio_id", String(64), nullable=False),
    Column("name", String(255), nullable=True),
    Column("state", String(64), nullable=True),
    Column("budget_scope", String(32), nullable=True),
    Column("daily_budget", Numeric(18, 6), nullable=True),
    Column("monthly_budget", Numeric(18, 6), nullable=True),
    Column("currency_code", String(16), nullable=True),
    Column("budget_policy", String(64), nullable=True),
    Column("in_budget", Boolean, nullable=True),
    Column("serving_status", String(64), nullable=True),
    Column("campaign_unspent_budget_sharing_state", String(64), nullable=True),
    Column("status_reasons_json", JSON, nullable=False, server_default=text("'[]'")),
    Column("budget_start_date", Date, nullable=True),
    Column("budget_end_date", Date, nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_refreshed_at", DateTime(timezone=True), nullable=False),
    PrimaryKeyConstraint("profile_id", "portfolio_id"),
)

sp_campaign = Table(
    "sp_campaign",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("campaign_id", String(64), nullable=False),
    Column("portfolio_id", String(64), nullable=True),
    Column("name", String(255), nullable=True),
    Column("state", String(64), nullable=True),
    Column("serving_status", String(64), nullable=True),
    Column("budget", Numeric(18, 6), nullable=True),
    Column("budget_type", String(64), nullable=True),
    Column("start_date", Date, nullable=True),
    Column("end_date", Date, nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_refreshed_at", DateTime(timezone=True), nullable=False),
    PrimaryKeyConstraint("profile_id", "campaign_id"),
)

Index("ix_sp_campaign_profile_portfolio", sp_campaign.c.profile_id, sp_campaign.c.portfolio_id)

sp_ad_group = Table(
    "sp_ad_group",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("ad_group_id", String(64), nullable=False),
    Column("campaign_id", String(64), nullable=False),
    Column("name", String(255), nullable=True),
    Column("state", String(64), nullable=True),
    Column("default_bid", Numeric(18, 6), nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_refreshed_at", DateTime(timezone=True), nullable=False),
    PrimaryKeyConstraint("profile_id", "ad_group_id"),
)

sp_keyword = Table(
    "sp_keyword",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("keyword_id", String(64), nullable=False),
    Column("campaign_id", String(64), nullable=False),
    Column("ad_group_id", String(64), nullable=False),
    Column("keyword_text", Text, nullable=True),
    Column("match_type", String(32), nullable=True),
    Column("current_bid", Numeric(18, 6), nullable=True),
    Column("bid_refreshed_at", DateTime(timezone=True), nullable=True),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_refreshed_at", DateTime(timezone=True), nullable=False),
    PrimaryKeyConstraint("profile_id", "keyword_id"),
)

sp_keyword_performance_fact = Table(
    "sp_keyword_performance_fact",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("window_start", Date, nullable=False),
    Column("window_end", Date, nullable=False),
    Column("keyword_id", String(64), nullable=False),
    Column("campaign_id", String(64), nullable=False),
    Column("ad_group_id", String(64), nullable=False),
    Column("keyword_text", Text, nullable=True),
    Column("match_type", String(32), nullable=True),
    Column("current_bid", Numeric(18, 6), nullable=True),
    Column("impressions", Float, nullable=True),
    Column("clicks", Float, nullable=True),
    Column("spend", Numeric(18, 6), nullable=True),
    Column("sales_14d", Numeric(18, 6), nullable=True),
    Column("orders_14d", Float, nullable=True),
    Column("last_report_run_id", String(36), nullable=True),
    Column("retrieved_at", DateTime(timezone=True), nullable=False),
    PrimaryKeyConstraint("profile_id", "window_start", "window_end", "keyword_id"),
)

sp_search_term_fact = Table(
    "sp_search_term_fact",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("window_start", Date, nullable=False),
    Column("window_end", Date, nullable=False),
    Column("campaign_id", String(64), nullable=False),
    Column("ad_group_id", String(64), nullable=False),
    Column("normalized_search_term", Text, nullable=False),
    Column("keyword_id", String(64), nullable=True),
    Column("search_term", Text, nullable=True),
    Column("match_type", String(32), nullable=True),
    Column("impressions", Float, nullable=True),
    Column("clicks", Float, nullable=True),
    Column("spend", Numeric(18, 6), nullable=True),
    Column("sales_14d", Numeric(18, 6), nullable=True),
    Column("orders_14d", Float, nullable=True),
    Column("manually_targeted", Boolean, nullable=True),
    Column("negated", Boolean, nullable=True),
    Column("targeting_context_json", JSON, nullable=False, server_default=text("'{}'")),
    Column("last_report_run_id", String(36), nullable=True),
    Column("retrieved_at", DateTime(timezone=True), nullable=False),
    PrimaryKeyConstraint(
        "profile_id",
        "window_start",
        "window_end",
        "campaign_id",
        "ad_group_id",
        "normalized_search_term",
    ),
)

sp_campaign_budget_history_fact = Table(
    "sp_campaign_budget_history_fact",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("campaign_id", String(64), nullable=False),
    Column("budget_date", Date, nullable=False),
    Column("campaign_name", String(255), nullable=True),
    Column("daily_budget", Numeric(18, 6), nullable=True),
    Column("spend", Numeric(18, 6), nullable=True),
    Column("utilization_pct", Float, nullable=True),
    Column("hours_ran", Float, nullable=True),
    Column("last_report_run_id", String(36), nullable=True),
    Column("retrieved_at", DateTime(timezone=True), nullable=False),
    PrimaryKeyConstraint("profile_id", "campaign_id", "budget_date"),
)

sp_placement_fact = Table(
    "sp_placement_fact",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("window_start", Date, nullable=False),
    Column("window_end", Date, nullable=False),
    Column("campaign_id", String(64), nullable=False),
    Column("placement_type", String(64), nullable=False),
    Column("campaign_name", String(255), nullable=True),
    Column("impressions", Float, nullable=True),
    Column("clicks", Float, nullable=True),
    Column("spend", Numeric(18, 6), nullable=True),
    Column("sales_14d", Numeric(18, 6), nullable=True),
    Column("purchases_14d", Float, nullable=True),
    Column("current_top_of_search_multiplier", Float, nullable=True),
    Column("current_product_pages_multiplier", Float, nullable=True),
    Column("context_retrieved_at", DateTime(timezone=True), nullable=True),
    Column("last_report_run_id", String(36), nullable=True),
    PrimaryKeyConstraint(
        "profile_id",
        "window_start",
        "window_end",
        "campaign_id",
        "placement_type",
    ),
)

sp_impression_share_fact = Table(
    "sp_impression_share_fact",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("window_start", Date, nullable=False),
    Column("window_end", Date, nullable=False),
    Column("campaign_id", String(64), nullable=False),
    Column("campaign_name", String(255), nullable=True),
    Column("top_of_search_impression_share", Float, nullable=True),
    Column("availability_state", String(32), nullable=True),
    Column("availability_reason", Text, nullable=True),
    Column("diagnostic_json", JSON, nullable=False, server_default=text("'{}'")),
    Column("last_report_run_id", String(36), nullable=True),
    Column("retrieved_at", DateTime(timezone=True), nullable=False),
    PrimaryKeyConstraint("profile_id", "window_start", "window_end", "campaign_id"),
)

portfolio_budget_usage_snapshot = Table(
    "portfolio_budget_usage_snapshot",
    metadata,
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("portfolio_id", String(64), nullable=False),
    Column("snapshot_timestamp", DateTime(timezone=True), nullable=False),
    Column("cap_amount", Numeric(18, 6), nullable=True),
    Column("current_spend", Numeric(18, 6), nullable=True),
    Column("remaining_budget", Numeric(18, 6), nullable=True),
    Column("utilization_pct", Float, nullable=True),
    Column("usage_updated_timestamp", DateTime(timezone=True), nullable=True),
    Column("availability_state", String(32), nullable=True),
    Column("availability_reason", Text, nullable=True),
    Column("diagnostic_json", JSON, nullable=False, server_default=text("'{}'")),
    PrimaryKeyConstraint("profile_id", "portfolio_id", "snapshot_timestamp"),
)

ingestion_job = Table(
    "ingestion_job",
    metadata,
    Column("ingestion_job_id", String(36), primary_key=True),
    Column("job_key", String(128), nullable=False),
    Column("job_type", String(64), nullable=False),
    Column("surface_name", String(128), nullable=False),
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("region", String(8), nullable=False),
    Column("window_start", Date, nullable=True),
    Column("window_end", Date, nullable=True),
    Column("scheduled_at", DateTime(timezone=True), nullable=False),
    Column("claimed_at", DateTime(timezone=True), nullable=True),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("last_heartbeat_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("status", String(32), nullable=False),
    Column("attempt_count", Integer, nullable=False, server_default=text("0")),
    Column("worker_id", String(128), nullable=True),
    Column("scope_json", JSON, nullable=False, server_default=text("'{}'")),
    Column("last_error_text", Text, nullable=True),
    Column("diagnostic_json", JSON, nullable=False, server_default=text("'{}'")),
    UniqueConstraint("job_key"),
    CheckConstraint("attempt_count >= 0", name="attempt_count_non_negative"),
)

report_run = Table(
    "report_run",
    metadata,
    Column("report_run_id", String(36), primary_key=True),
    Column("ingestion_job_id", String(36), ForeignKey("ingestion_job.ingestion_job_id"), nullable=False),
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("window_start", Date, nullable=True),
    Column("window_end", Date, nullable=True),
    Column("amazon_report_id", String(64), nullable=True),
    Column("surface_name", String(128), nullable=False),
    Column("report_type_id", String(128), nullable=False),
    Column("request_scope_hash", String(64), nullable=False),
    Column("active_scope_key", String(255), nullable=True, unique=True),
    Column("status", String(32), nullable=False),
    Column("raw_status", String(64), nullable=True),
    Column("status_details", Text, nullable=True),
    Column("requested_at", DateTime(timezone=True), nullable=False),
    Column("last_polled_at", DateTime(timezone=True), nullable=True),
    Column("completed_at", DateTime(timezone=True), nullable=True),
    Column("retrieved_at", DateTime(timezone=True), nullable=True),
    Column("row_count", Integer, nullable=True),
    Column("error_text", Text, nullable=True),
    Column("diagnostic_json", JSON, nullable=False, server_default=text("'{}'")),
)

freshness_watermark = Table(
    "freshness_watermark",
    metadata,
    Column("surface_name", String(128), nullable=False),
    Column("profile_id", String(64), ForeignKey("ads_profile.profile_id"), nullable=False),
    Column("region", String(8), nullable=False),
    Column("last_successful_window_end", Date, nullable=True),
    Column("last_snapshot_at", DateTime(timezone=True), nullable=True),
    Column("last_attempted_at", DateTime(timezone=True), nullable=True),
    Column("last_status", String(32), nullable=True),
    Column("notes_json", JSON, nullable=False, server_default=text("'{}'")),
    PrimaryKeyConstraint("surface_name", "profile_id", "region"),
)

all_tables = [
    ads_profile,
    portfolio,
    sp_campaign,
    sp_ad_group,
    sp_keyword,
    sp_keyword_performance_fact,
    sp_search_term_fact,
    sp_campaign_budget_history_fact,
    sp_placement_fact,
    sp_impression_share_fact,
    portfolio_budget_usage_snapshot,
    ingestion_job,
    report_run,
    freshness_watermark,
]

Index("ix_ingestion_job_profile_surface_status", ingestion_job.c.profile_id, ingestion_job.c.surface_name, ingestion_job.c.status)
Index("ix_report_run_scope_status", report_run.c.profile_id, report_run.c.report_type_id, report_run.c.request_scope_hash, report_run.c.status)
